spring:
  sql:
    init:
      data-locations: classpath:sql/data.sql
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: r2dbc:h2:mem:///userdb
#    username: sa
#    password: password

sec: sec04
